### ISSUE TITLE
Is this system compatible with VictoriaMetrics ?

### ISSUE THREAD

**Issue by denisgolius** [mattogodoy/omni#1]
I know that there is a  practice to write data by Influx protocol into InfluxDB. Also I know that InfluxDB have an issues with high RAM consumption on running device. 
Is this system compatible with [VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics) ?
Because it can be run as simple binary file and as I know it [requires less memory and cpu ](https://victoriametrics.github.io/FAQ.html?highlight=influx#how-does-victoriametrics-compare-to-influxdb).

**Comment by mattogodoy** [comment]
I'm sorry to say that it's not compatible with VictoriaMetrics because [I'm using InfluxDB's client library](https://github.com/mattogodoy/omni/blob/master/src/main.py#L5-L15) to store the information, but I guess you could easily fork this repo and change that part of the code to send the data to any other database. You'll just have to modify the information to a format that VictoriaMetrics could understand and that's it. All of the rest should be the same.

**Comment by denisgolius** [comment]
> I'm sorry to say that it's not compatible with VictoriaMetrics because [I'm using InfluxDB's client library](https://github.com/mattogodoy/omni/blob/master/src/main.py#L5-L15) to store the information, but I guess you could easily fork this repo and change that part of the code to send the data to any other database. You'll just have to modify the information to a format that VictoriaMetrics could understand and that's it. All of the rest should be the same.

Thanks for a fast feedback.

I think it must works without fixes in code base https://victoriametrics.github.io/Single-server-VictoriaMetrics.html#how-to-send-data-from-influxdb-compatible-agents-such-as-telegraf .

**Comment by denisgolius** [comment]
If you interested to make it compatible with [VM](https://github.com/VictoriaMetrics/VictoriaMetrics) I'm ready to help.

**Comment by mattogodoy** [comment]
Well, in that case it seems like it could work, that's good news!
Sure, if you want to try it out and make a Pull Request I'll happily review it :)
